#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/../common/pywrap", sys.argv)

import subprocess
import sys

import testlib


class TestOpenVPNPlayground(testlib.MachineCase):
    provision = {
            "machine1": {"address": "192.168.100.11/24", "restrict": False},
            "machine2": {"address": "192.168.100.12/24", "restrict": False},
    }

    def testOpenvpn(self):
        m1 = self.machines["machine1"]
        m2 = self.machines["machine2"]

        # increasing productivity
        m1.execute("echo 'export dir=/usr/share/doc/openvpn/examples/sample-keys' >> .bashrc")
        m1.execute("sed -i 's/nameserver 127.0.0.1/nameserver 8.8.8.8/' /etc/resolv.conf")

        ovpn_conf = """ "# start
client
dev tun
remote 192.168.100.12 1194 udp
remote 192.168.100.12 443 tcp

data-ciphers-fallback BF-CBC # this was needed to make the client directive work

remote-cert-tls server
# cipher AES-256-CBC
# auth SHA256
# -> ping fails with the above two
persist-tun
socket-flags TCP_NODELAY
push-peer-info

ifconfig 10.4.0.1 10.4.0.2
tls-client

ca ca.crt
cert client.crt
key client.key
        " """
        m1.execute(f"echo {ovpn_conf} >> /usr/share/doc/openvpn/examples/sample-keys/test.ovpn")
        # m1.execute("cd $dir && nmcli connection import type openvpn file test.ovpn")
        m1.execute("cp /usr/share/doc/openvpn/examples/sample-config-files/client.conf /usr/share/doc/openvpn/examples/sample-keys/client.ovpn")
        # m1.execute("cd /usr/share/doc/openvpn/examples/sample-keys && nohup openvpn --config test-connection.ovpn &");
        # m1.execute("nohup openvpn --remote 192.168.100.12 --dev tun1 --ifconfig 10.4.0.1 10.4.0.2 --tls-client --ca ca.crt --cert client.crt --key client.key &")
        server_conf = """ "
remote 192.168.100.11
dev tun1
ifconfig 10.4.0.2 10.4.0.1
tls-server

dh /usr/share/doc/openvpn/examples/sample-keys/dh2048.pem

ca /usr/share/doc/openvpn/examples/sample-keys/ca.crt

cert /usr/share/doc/openvpn/examples/sample-keys/server.crt

key /usr/share/doc/openvpn/examples/sample-keys/server.key
        " """
        m2.execute(f"echo {server_conf} >> /etc/openvpn/server.conf")
        m2.execute("systemctl enable --now openvpn@server")
        #
        # m1.execute("ping -c 1 10.4.0.2")

        testlib.sit()

if __name__ == "__main__":
    testlib.test_main()
