#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/../common/pywrap", sys.argv)

import subprocess
import sys

import testlib


# Deps: openvpn, network-manager-openvpn, easy-rsa (optional)
class TestOpenVPNPlayground(testlib.MachineCase):
    provision = {
            "machine1": {"address": "192.168.100.11/24", "restrict": False},
            "machine2": {"address": "192.168.100.12/24", "restrict": False},
    }

    def testOpenvpn(self):
        m1 = self.machines["machine1"]
        m2 = self.machines["machine2"]

        # increasing productivity
        keys_dir = "/usr/share/doc/openvpn/examples/sample-keys"
        m1.execute("touch .hushlogin")
        m2.execute("touch .hushlogin")

        # SERVER
        server_conf = """ "
port 1194
proto udp
dev tun

ca /usr/share/doc/openvpn/examples/sample-keys/ca.crt
cert /usr/share/doc/openvpn/examples/sample-keys/server.crt
key /usr/share/doc/openvpn/examples/sample-keys/server.key
dh /usr/share/doc/openvpn/examples/sample-keys/dh2048.pem

server 10.8.0.0 255.255.255.0
tls-server

keepalive 10 120
data-ciphers-fallback AES-256-CBC

persist-key
persist-tun
        " """
        m2.execute(f"echo {server_conf} >> /etc/openvpn/server.conf")
        m2.execute("systemctl enable --now openvpn@server")
        m2.execute("firewall-cmd --add-port=1194/udp")

        # create .ovpn file for client
        ovpn_conf = """ "# start
client
dev tun
proto udp
remote 192.168.100.12 1194 udp
resolv-retry infinite
persist-key
persist-tun
remote-cert-tls server
data-ciphers-fallback AES-256-CBC
        " """
        m2.execute(f"echo {ovpn_conf} >> {keys_dir}/test.ovpn")
        m2.execute(f"echo '<ca>' >> {keys_dir}/test.ovpn")
        m2.execute(f"cat {keys_dir}/ca.crt >> {keys_dir}/test.ovpn")
        m2.execute(f"echo '</ca>' >> {keys_dir}/test.ovpn")

        m2.execute(f"echo '<cert>' >> {keys_dir}/test.ovpn")
        m2.execute(f"cat {keys_dir}/client.crt >> {keys_dir}/test.ovpn")
        m2.execute(f"echo '</cert>' >> {keys_dir}/test.ovpn")
        
        m2.execute(f"echo '<key>' >> {keys_dir}/test.ovpn")
        m2.execute(f"cat {keys_dir}/client.key >> {keys_dir}/test.ovpn")
        m2.execute(f"echo '</key>' >> {keys_dir}/test.ovpn")

        # download the .ovpn file from the server to client
        m1.execute("ssh-keygen -t ed25519 -C '<comment>' -f '/root/.ssh/id_ed25519' -N ''")
        pubkey = m1.execute("cat .ssh/id_ed25519.pub")
        m2.execute(f"echo '{pubkey.strip()}' >> .ssh/authorized_keys")
        m1.execute(f"scp -o StrictHostKeyChecking=accept-new 192.168.100.12:{keys_dir}/test.ovpn .")

        m1.spawn("openvpn test.ovpn", "openvpn_log")
        m1.execute("sleep 10; ping -c 1 10.8.0.1")

if __name__ == "__main__":
    testlib.test_main()
